### PR TITLE
Update fes1

### PR DESCRIPTION
**Pull request by DanTheMan827**

### CODE REVIEW

**Comment by JackHell1** [comment]
Please, somebody! 
Why is there a warning about the number of items in a folder in red in the structure window at the bottom? There are 150 games in the HOME menu and I see red text at the bottom telling me about it. I still synchronized the games in this version and everything seems to be working fine. Are there any consequences for ignoring the red warning? I use HAKCHI2 CE for SEGA Genesis mini.

**Comment by JackHell1** [comment]
Please, somebody! 
Why is there a warning about the number of items in a folder in red in the structure window at the bottom? There are 150 games in the HOME menu and I see red text at the bottom telling me about it. I still synchronized the games in this version and everything seems to be working fine. Are there any consequences for ignoring the red warning? I use HAKCHI2 CE for SEGA Genesis mini.

**Comment by DanTheMan827** [comment]
There's no real limit that anyone is likely to reach in the genesis mini, but things start to slow down at a certain point

**Comment by JackHell1** [comment]
> 

Thnx!!! )))

**Pull request closed without merging**
