### PR TITLE
Database files for various systems

### PR DESCRIPTION
**Pull request by edimusxero**
I have created database files for the following systems

- sega genesis / master drive

- atari 2600 / 5200 / 7800

- Nintendo gameboy / gameboy advance

More are in the process.  No back end coding to implement them into hakchi has been written, but I wanted to provide the xml files.

### CODE REVIEW

**Comment by daPhie79** [comment]
i'm interested for sure. although this PR as it is is unusable. you could maybe zip the data files and attach it with a comment reply? i will do what i can to integrate them when i can!

**Comment by edimusxero** [comment]
Sure thing, wasn't sure how you wanted the data.  I am still working on piecing together more databases bit busy at work right now.  Here are a few zipped for you.

[carts archive.zip](https://github.com/TeamShinkansen/hakchi2/files/1939939/carts.archive.zip)

**Comment by daPhie79** [comment]
thank you! when i have time i'll try to see how i can integrate additional databases!

**Comment by DanTheMan827** [comment]
@edimusxero thank you for the xml files!

How are those generated, or where are those XML files from?

**Comment by skogaby** [comment]
@edimusxero I'd be *very* interested to see how those are generated. I tried doing this myself for various systems, including some of the ones you've done. However, I had issues because I couldn't get CRC32 from thegamesdb API and I had to try to cross-reference thegamesdb with screenscraper.fr and had a lot of false positives/negatives when trying to cross reference them

**Comment by edimusxero** [comment]
Most the metadata is from thegamesdb and the crc32 check sums are pulled from dat files found on http://datomatic.no-intro.org/.

I basically wrote a php script to dump ALL the data from thegamesdb into a database and the used a perl script to match the checksums.  The script wasn't 100% perfect (because it relied on a name matching so Japan roms and US roms of the same name would step on each others toes).  I reworked my process and basically had to run the script twice while changing some code (ugly but I didn't want to waste too much time on the script).  The dat files give you the info like the name, region, checksum, release dates etc. but to get the info for number of players art work etc. I had to have it cross reference thegamesdb.

I can post the scripts I used if you want to see it.

**Comment by skogaby** [comment]
@edimusxero If you wouldn't mind posting those scripts, that'd be fantastic. I was coding something simililar by cross-referencing thegamesdb and screenscraper using fuzzy matching on the names, but I had a lot of false matches and negatives.

**Comment by edimusxero** [comment]
Here are the scripts I used.  They are ugly and may require some manual intervention.  I didn't spend a lot of time on them because I didn't know if the outcome was going to be viable.  

** Updated **

Added the sql file of the database I use

[scripts.zip](https://github.com/TeamShinkansen/hakchi2/files/1947931/scripts.zip)

**Comment by edimusxero** [comment]
I wrapped the load_meta.php file in a a shell script like so (cause I didn't write that asynchronously) to load the games WAY faster

    #!/bin/bash
        count=0
        while [ $count -le 100 ]; do
            /usr/bin/php -f load_meta.php > /dev/null 2>&1 &
            (( count++ ))
        sleep 1
    done

**Pull request closed without merging**
